# An example of ClusterConfig object with custom VPC IPv4 CIDR,
# and auto-allocated IPv6 CIDRs for all subnets; also without
# any nodegroups:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: false
  # disable public access to endpoint and only allow private access
#  clusterEndpoints:
#    publicAccess: true
#    privateAccess: true
# availabilityZones: ["us-east-1a", "us-east-1b",  "us-east-1c"] 
nodeGroups: []
