apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-1
  region: us-east-1
managedNodeGroups:
  - name: gpu-Spot-p2-xlarge
    spot: true
    minSize: 1
    maxSize: 2
#    desiredCapacity: 1
    instanceTypes: ["p2.xlarge"]
    amiFamily: AmazonLinux2    
    labels:
      workgroup: p2-2xlarge
      lifecycle: Spot
      aws.amazon.com/spot: "false"
      gpu-count: "1" 
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Spot
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "false"
      k8s.io/cluster-autoscaler/node-template/label/gpu-count: "1"
      k8s.io/cluster-autoscaler/node-template/label/workgroup: p2-xlarge
      k8s.io/cluster-autoscaler/enabled: "true"   
    iam:
      withAddonPolicies:
        autoScaler: true 