# Run this workflow on:
# - Merge Requests
# - Commits to the "master" branch
# - Commits to the "releases" branch
# - Tags
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^release/
    - if: $CI_COMMIT_TAG

# TP GitLab CI templates
#include:
#  - project: "ci/gitlab-templates"
#    file: "/.gitlab-ci-template.yml"

# Global variables
variables:
  DOCKER_NAME: "proxysql"

stages:
  - prepare
  - deploy

###############
### Prepare ###
###############

dco:
#  extends: .dco-template
  stage: prepare

build-tag:
#  extends: .build-tag-template
  stage: prepare

##############
### Deploy ###
##############

deploy-stg:
  stage: deploy
  extends: .kaniko-k8s-deploy-template
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: manual
      allow_failure: true
  variables:
    DEPLOYMENT_TEMPLATE: ".gitlab/templates/k8s/stg-template.yml"
    DEPLOYMENT_NAME: "${DOCKER_NAME}"
    DEPLOYMENT_IMAGE: "SET_IN_TEMPLATE"
    PROXYSQL_ADMIN_USER: "${STG_PROXYSQL_ADMIN_USER}"
    PROXYSQL_ADMIN_PASSWORD: "${STG_PROXYSQL_ADMIN_PASSWORD}"
    PROXYSQL_MONITOR_USER: "${STG_PROXYSQL_MONITOR_USER}"
    PROXYSQL_MONITOR_PASSWORD: "${STG_PROXYSQL_MONITOR_PASSWORD}"
    PROXYSQL_CLUSTER_USERNAME: "${STG_PROXYSQL_CLUSTER_USERNAME}"
    PROXYSQL_CLUSTER_PASSWORD: "${STG_PROXYSQL_CLUSTER_PASSWORD}"
    PROXYSQL_STATS_USERNAME: "${STG_PROXYSQL_STATS_USERNAME}"
    PROXYSQL_STATS_PASSWORD: "${STG_PROXYSQL_STATS_PASSWORD}"
    MYSQL_API_USER_NAME: "${STG_MYSQL_API_USER_NAME}"
    MYSQL_API_USER_PASSWORD: "${STG_MYSQL_API_USER_PASSWORD}"
    MYSQL_API_RO_USER_NAME: "${STG_MYSQL_API_RO_USER_NAME}"
    MYSQL_API_RO_USER_PASSWORD: "${STG_MYSQL_API_RO_USER_PASSWORD}"
    MYSQL_KEYCLOAK_USER_NAME: "${STG_MYSQL_KEYCLOAK_USER_NAME}"
    MYSQL_KEYCLOAK_USER_PASSWORD: "${STG_MYSQL_KEYCLOAK_USER_PASSWORD}"
    MYSQL_QTEST_USER_NAME: "${STG_MYSQL_QTEST_USER_NAME}"
    MYSQL_QTEST_USER_PASSWORD: "${STG_MYSQL_QTEST_USER_PASSWORD}"
    MYSQL_MATOMO_USER_NAME: ${STG_MYSQL_MATOMO_USER_NAME}
    MYSQL_MATOMO_USER_PASSWORD: ${STG_MYSQL_MATOMO_USER_PASSWORD}
