apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-1
  region: us-east-1
managedNodeGroups:
  - name: gpu-spot-g3s-xlarge
    spot: true
    minSize: 2
    maxSize: 3
    instanceTypes: ["g3s.xlarge"]
    amiFamily: AmazonLinux2    
    labels:
      workgroup: g3s-xlarge
      lifecycle: Ec2Spot
      aws.amazon.com/spot: "true"
      gpu-count: "1" 
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
      k8s.io/cluster-autoscaler/node-template/label/gpu-count: "1"
      k8s.io/cluster-autoscaler/node-template/label/workgroup: g3s-xlarge
      k8s.io/cluster-autoscaler/enabled: "true"   
    iam:
      withAddonPolicies:
        autoScaler: true 